# Generated by Django 4.0.5 on 2022-07-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_gettinginvolvedlead_college_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='importantupdate',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='owns_a_computer',
            field=models.TextField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=2550, null=True),
        ),
    ]
