# Generated by Django 4.0.5 on 2022-07-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_membershipapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplication',
            name='application_letter',
            field=models.FileField(null=True, upload_to='Application Letters'),
        ),
    ]
